distribution: trixie
lb:
  aptRecommends: true
  win32Loader: false # win32-loader not supported on trixie distributions 
overlays:
  Networking: {}
  Networking+VPN: {}
  Desktop Environment: {}
  Desktop Environment+Shell: {}
  Desktop Environment+Tweaks: {}
  Desktop Environment+Phone Sync: {}
  Terminal: {}