distribution: trixie
lb:
  aptRecommends: true
  aptOptions: "-y -o APT::Default-Release=trixie" # NOTE: Default release should be the same as distribution
  win32Loader: false # win32-loader not supported on trixie distributions 
overlays:
  Networking: {}
  Networking+VPN: {}
  Desktop Environment: {}
  Desktop Environment+Shell: {}
  Desktop Environment+Tweaks: {}
  Desktop Environment+Phone Sync: {}
  Desktop Environment+Window Tiling: {}
  Desktop Environment+Theming: {}
  Terminal: {}
  Display Manager: {}
  Text Editor: {}
  Remote Desktop: {}
  Flatpaks:
    packages:
      - com.parsecgaming.parsec
  Remote Desktop+Rustdesk:
    configPaths:
      RustDeskToml: /run/live/medium/RustDesk.toml # Configure RustDesk at the live medium directory
      RustDesk2Toml: /run/live/medium/RustDesk2.toml
  Browser:
    chromium:
      installWebStore: true
  Browser+Ad blocking:
    extensions:
      google-chrome:
        - id: ddkjiahejlhfcafbddmgiahcphecmpfh
          name: uBlock Origin Lite
  Browser+Password Management:
    extensions:
      firefox:
        - id: "{446900e4-71c2-419f-a6a7-df9c091e268b}"
          name: Bitwarden
        - id: "78272b6fa58f4a1abaac99321d503a20@proton.me"
          name: Proton Pass
      google-chrome:
        - id: nngceckbapebfimnlniiiahkandclblb
          name: Bitwarden
        - id: ghmbeldphafepmbegfdlkpapadhbakde
          name: Proton Pass
      chromium:
        - id: nngceckbapebfimnlniiiahkandclblb
          name: Bitwarden
        - id: ghmbeldphafepmbegfdlkpapadhbakde
          name: Proton Pass