distribution: trixie
lb:
  aptRecommends: true
  aptOptions: "-y -o APT::Default-Release=trixie" # NOTE: Default release should be the same as distribution
  win32Loader: false # win32-loader not supported on trixie distributions 
overlays:
  Networking: {}
  Networking+VPN: {}
  Desktop Environment: {}
  Desktop Environment+Shell: {}
  Desktop Environment+Tweaks: {}
  Desktop Environment+Phone Sync: {}
  Desktop Environment+Window Tiling: {}
  Desktop Environment+Theming: {}
  Terminal: {}
  Display Manager: {}
  Text Editor: {}
  Flatpaks:
    packages:
      - com.parsecgaming.parsec