# This is a basic workflow to help you get started with Actions

name: build-livecd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Cache nix with
      # https://github.com/marketplace/actions/magic-nix-cache
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      # Runs a single command using the runners shell
      - name: Install NixOS image builder
        run: nix profile install github:nix-community/nixos-generators

      # Runs a set of commands using the runners shell
      - name: Save and Build NixOS Image
        run:  echo "IMAGE_PATH=$(nixos-generate -f proxmox-lxc -c configuration.nix)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: livecd-proxmox-lxc
          path: ${{ env.IMAGE_PATH }}
