configPaths: # The expected location of the RustDesk TOML configuration files. Setting it to /run/live/medium is a special configuration where the path symbolically corresponds to the root of the underlying filesystem containing the ISO contents.
  RustDeskToml: /run/live/medium/RustDesk.toml
  RustDesk2Toml: /run/live/medium/RustDesk2.toml
